cb - documented our decided tech stack
ucsb-cs148-f21/project-t10-animelist pull request #15
Opened 2021-10-11 21:54 UTC by christopherbarnett

2021-10-11 22:34 UTC, rowantran requested changes
LGTM. can you also add that we're using MongoDB for the database?

2021-10-12 06:09 UTC, jvoucsb approved these changes

2021-10-12 06:11 UTC, jvoucsb requested changes
looks good excellent excellent. I see that the change is in #38 with the rest so merge that in instead. excellent

2021-10-13 04:32 UTC, christopherbarnett commented
cb - i agree

2021-10-13 04:32 UTC, closed without merging